### ISSUE TITLE
1.20.1 - Crashing server when damaged with Ars Elemental Armor

### ISSUE THREAD

**Issue by ToxinZangoose** [Alexthw46/Ars-Elementals#66]
[crash-2024-09-10_18.20.54-server.txt](https://github.com/user-attachments/files/16949217/crash-2024-09-10_18.20.54-server.txt)

Crash log is attached, tested on a server with Forge 47.3.7.
This is the first issue our server has had with Ars Elemental, if there is anything else I need to send to you, let me know.

**Comment by Alexthw46** [comment]
Since the crash is actually Watchdog (a thing in minecraft servers checking if something is taking too long) reaching the time limit and killing the server, it doesn't say where the problem is, so it could be anything. As 1.19 is quite mature, if there is an actual issue it's likely a mod conflict of some sort... similar trigger for a crash was recently reported with Deeper and Darker and it was their problem to fix. Unsure on how to help

**Comment by ToxinZangoose** [comment]
Ok, I understand. Thank you for your time.
