### ISSUE TITLE
(0.6.7.5) Earth bangle does not protect against berry bushes

### ISSUE THREAD

**Issue by Owlfren** [Alexthw46/Ars-Elementals#81]
Earth bangle does not protect against berry bushes in 0.6.7.5. Tested on sweet-berry and source-berry bushes. Book claims it does.

How to replicate: Enter creative, get an earth bangle, put it on, walk into a fully grown bush.

**Comment by Alexthw46** [comment]
Have you tried with just ars, dependencies and elemental? the bangle protects me as intended in my world

**Comment by Owlfren** [comment]
I have now run it with only AN, Elemental, and Forge Curios and have narrowed it down. If the Earth bangle is placed second, after an Air Bangle (possibly others, had limited time for testing) it does not protect you. If it is placed first or alone it seems to work.

ars_elemental-1.20.1-0.6.7.5
ars_nouveau-1.20.1-4.12.6-all
curios-forge-5.10.0+1.20.1

**Comment by Alexthw46** [comment]
oh that explains it, it's a limit of the bangle element check as it returns the element of the first bangle equipped. It was made back when only one bangle slot was available. It was raised to two later but since only two things use that check nobody reported. It might require a bit of time or be out tomorrow, i'll have to update the check on both versions that have two slots.

**Comment by Owlfren** [comment]
Mm. Might be an idea to make it check the number of relevant slots then iterate through them instead of a static check that only goes for X defined ones.
Anyways, glad I could help narrow it down! And also glad that I am not blessed with the ability to walk through bushes, even if it sacrifices the air bangle abilities.
